[package]
name = "task-executor"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
futures = "0.3.31"
rand = "0.8.5"
tokio = { version = "1.34.0", features = ["full"] }
